pretrained-vectors.md

Added pretrained-vectors.md with trained embeddings download links.

Added pretrained-vectors.md with trained embeddings download links

---

deeppavlov/core/common/attributes.py

feat: add wraps

---

deeppavlov/models/spellers/error_model/README.md

You can delete this branch after merge

fix: correct path names in description of the spelling correction module

---

deeppavlov/skills/go_bot/README.md

- rm run_model
- fix use_action_mask
- add metrics

docs: fix go-bot docs for release

---

deeppavlov/models/classifiers/intents/README.md

docs: change running from run_model.py to deep.py

---

deeppavlov/configs/error_model/config_en.json
deeppavlov/configs/error_model/config_ru.json
deeppavlov/configs/error_model/config_ru_custom_vocab.json
deeppavlov/configs/go_bot/config.json
deeppavlov/configs/go_bot/config_all.json
deeppavlov/configs/go_bot/config_minimal.json
deeppavlov/configs/go_bot/config_train.json
deeppavlov/configs/intents/config_dstc2_infer.json
deeppavlov/configs/intents/config_dstc2_train.json
deeppavlov/configs/intents/config_snips.json
deeppavlov/configs/ner/ner_conll2003_train.json
deeppavlov/configs/ner/ner_dstc2_train.json
deeppavlov/configs/ner/slot_config.json
deeppavlov/configs/ner/slot_config_train.json
deeppavlov/core/commands/train.py
deeppavlov/core/commands/utils.py
deeppavlov/core/common/paths.py
deeppavlov/core/models/serializable.py
deeppavlov/dataset_readers/babi_dataset_reader.py
deeppavlov/datasets/dstc2_datasets.py
deeppavlov/deep.py
deeppavlov/download.py
deeppavlov/models/ner/NER_README.md
deeppavlov/models/ner/README.md
deeppavlov/models/spellers/error_model/README.md
deeppavlov/models/trackers/hcn_at.py
deeppavlov/run_model.py
deeppavlov/skills/go_bot/README.md
deeppavlov/skills/go_bot/go_bot.py
deeppavlov/vocabs/typos.py

rename `user_dir` to `deeppavlov_root` and use it as a base for relative paths in configs

Deeppavlov root

---

deeppavlov/models/ner/README.md

seems like the example is a bit mislabelled.

Small fix to NER README

---

deeppavlov/configs/intents/intents_snips.json
deeppavlov/dataset_readers/classification_dataset_reader.py
deeppavlov/models/classifiers/intents/README.md
deeppavlov/run_model.py

delete parameters from classification_datasetreader because previously it could not read anything except train

fix: delete parameters from classification_datasetreader

---

README.md

docs: correct paths to scripts and configs to be relative to repository root

---

telegram_utils/telegram_ui.py

fix: telegram interact does not depend on cwd

---

setup.py

fix: use requirements generator only once

---

deeppavlov/core/commands/train.py

refactor: more stable and consistent code

---

deeppavlov/core/commands/train.py

Test passed, except test 33 (not enough memory on my GPU, should pass on other machines).

Train script refactoring: improve typing, readability, remove code duplications, rename dataset->iterator

---

deeppavlov/__init__.py
deeppavlov/configs/ner/ner_conll2003.json
deeppavlov/configs/ner/ner_conll2003_emb.json
deeppavlov/configs/ner/ner_ontonotes_emb.json
deeppavlov/core/data/urls.py
deeppavlov/models/embedders/glove_embedder.py
deeppavlov/models/ner/network.py
tests/test_quick_start.py

Glove embedder and NER model support for pre-trained embeddings

Glove embedder

---

deeppavlov/core/layers/keras_layers.py

add keras additive and multiplicative layers

feat: add keras additive and multiplicative attention layers

---

deeppavlov/configs/odqa/odqa_infer_prod.json
deeppavlov/configs/odqa/ranker_prod.json
deeppavlov/dataset_iterators/sqlite_iterator.py
deeppavlov/vocabs/wiki_sqlite.py

ODQA Hotfix (renaming data in share)

---

deeppavlov/core/common/file.py

@dilyararimovna asked for this

feat: pretty print saved json files

---

deeppavlov/configs/odqa/en_odqa_infer_prod.json
deeppavlov/configs/odqa/en_ranker_prod.json
deeppavlov/configs/odqa/ru_odqa_infer_prod.json
deeppavlov/configs/odqa/ru_ranker_prod.json

Created new packages on share, changed names in configs.

feat: separate packages for en_odqa and ru_odqa

---

deeppavlov/__init__.py
deeppavlov/configs/odqa/en_odqa_infer_prod.json
deeppavlov/configs/odqa/en_ranker_prod.json
deeppavlov/configs/odqa/odqa_infer_test.json
deeppavlov/configs/odqa/ranker_test.json
deeppavlov/configs/odqa/ru_odqa_infer_prod.json
deeppavlov/configs/odqa/ru_ranker_prod.json
deeppavlov/skills/odqa/ranker.py
deeppavlov/skills/odqa/tfidf_ranker.py
deeppavlov/vocabs/wiki_sqlite.py

Main changes:
* Change tfidf ranker logic.
* Add `top_n` and `active` attributes to tfidf ranker.
* Simplify ODQA configs.
* Inherit SQLite vocab from SQLite iterator.

Fancy ODQA

---

deeppavlov/configs/go_bot/database_dstc2.json
deeppavlov/core/data/sqlite_database.py
deeppavlov/core/data/vocab.py
deeppavlov/skills/go_bot/README.md

Fix of go_bot not working for interactbot

---

README.md
deeppavlov/models/classifiers/intents/README.md

* Update README.md
* Update README.md
* Update README.md
* Delete CNAME
* Create CNAME
* Delete CNAME
* Create CNAME
* Delete CNAME
* Create CNAME
* Delete CNAME
* Create CNAME
* fix: change docs for classification
Classification docs should be read for Intent classification and also for sentiment. i.e for any classification  task.
* docs: add scores
* docs: change link to classification component
Removed intents in link

fix: change docs for classification

---

deeppavlov/models/slotfill/slotfill_raw.py

Set return_all=True in config to return all entities

feat: support of all entities return in raw_slotfill

---

deeppavlov/dataset_iterators/ranking_iterator.py

Add DataLearningIterator to RankingIterator

Ranking dataset iterator

---

Jenkinsfile
deeppavlov/core/data/utils.py
deeppavlov/dataset_readers/basic_classification_reader.py
tests/test_quick_start.py
utils/pip_wrapper/pip_wrapper.py

feat: add cache option for downloads to try and speed the tests up

---

deeppavlov/core/data/utils.py

feat: send an autogenerated token as a header with download requests

---

deeppavlov/models/classifiers/keras_classification_model.py

hot fix: making classifier on keras compatible with elmo embeddings

fix: hot fix, make classifier compatible with elmo embedder

---

examples/tutorials/03_deeppavlov_gobot.ipynb

[0.0.6.6 release](https://github.com/deepmipt/DeepPavlov/releases/tag/0.0.6.6) contained renaming of `dstc2_v2_reader` to `dstc2_reader`.
Fixing tutorial that explored the dataset.

fix: dstc2 rename fix

---

deeppavlov/core/commands/train.py

add validation before first epoch

feature: validate first in train

---

deeppavlov/core/models/keras_model.py
deeppavlov/core/models/tf_backend.py
deeppavlov/models/classifiers/keras_classification_model.py

Encapsulation of all KerasModel methods in graph and session for KERAS_BACKEND=tensorflow.

Fix / Multiple keras models in parallel

---

deeppavlov/evolve.py
tests/test_quick_start.py

Fix tests logging and evolution execution on windows

Fix tests logging and evolution execution on windows

---

dp_requirements/tf-gpu.txt
dp_requirements/tf.txt

Reverts deepmipt/DeepPavlov#489

Revert "Increase TensorFlow required version to 1.10"

---

deeppavlov/configs/go_bot/gobot_dstc2.json
deeppavlov/configs/go_bot/gobot_dstc2_minimal.json
deeppavlov/models/embedders/bow_embedder.py
deeppavlov/models/go_bot/bot.py

Refactor: Holy Inquisition 

---

deeppavlov/configs/squad/multi_squad_noans.json

Tests on Windows break otherwise

fix: change download urls for multi_squad_noans

---

deeppavlov/configs/doc_retrieval/en_ranker_tfidf_wiki.json
deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json
deeppavlov/configs/odqa/en_odqa_infer_wiki.json
deeppavlov/configs/odqa/ru_odqa_infer_wiki.json
deeppavlov/core/common/registry.json
deeppavlov/dataset_iterators/sqlite_iterator.py
deeppavlov/dataset_readers/odqa_reader.py
deeppavlov/vocabs/wiki_sqlite.py
docs/components/tfidf_ranking.rst
tests/test_configs/doc_retrieval/en_ranker_tfidf_wiki_test.json
tests/test_configs/odqa/en_odqa_infer_wiki_test.json
tests/test_quick_start.py

Key features:
* added `ODQADataReader` class
* parallel SQLite DB building from usual text data
* get rid of DrQa reference for DB building
* updated docs

ODQA Reader

---

deeppavlov/models/spelling_correction/levenshtein/searcher_component.py

feat: ignore single character punctuation when correcting spelling

---

deeppavlov/core/common/log.py

Removed potential cycle dependencies from logging module.

Fixed log.py: removed potential cycle dependencies

---

deeppavlov/models/embedders/tfidf_weighted_embedder.py

Now this component works does not fail if counter_vocab_path is specified.

fixed errors and updated docstrings

---

deeppavlov/core/commands/train.py
deeppavlov/deep.py

Tested it with `python -m deeppavlov train --recursive slotfill_dstc2 -d`

allow recursive training with a `--recursive` parameter

---

_layouts/default.html

https://yoptar.github.io/DeepPavlov/

docs: warn about cookies usage on github pages

---

deeppavlov/configs/classifiers/intents_snips.json

Change `downloads_path` to `models_path` for intents_snips model

fix: change variables for save and load paths of main model

---

deeppavlov/core/commands/train.py
deeppavlov/models/go_bot/network.py

fix: do not load from saved when evaluating model without training

---

deeppavlov/models/elmo/elmo.py
deeppavlov/models/embedders/elmo_embedder.py

wip (docs): add install docs to elmo_model/elmo_embedder.

---

.readthedocs.yml

[WIP] docs: add PDF format

---

deeppavlov/models/__init__.py
docs/devguides/settings.rst

feat: add an env var to skip nltk.download. close #634

---

docs/conf.py
docs/index.rst

[WIP] improve latex builder

---

deeppavlov/configs/ranking/ranking_default.json
deeppavlov/configs/ranking/ranking_default_triplet.json
deeppavlov/core/common/registry.json
deeppavlov/dataset_readers/siamese_default_reader.py
deeppavlov/dataset_readers/siamese_reader.py
deeppavlov/models/ranking/siamese_predictor.py
docs/apiref/dataset_readers.rst
docs/apiref/models/ranking.rst
docs/components/neural_ranking.rst

- default reader for ranking and paraphrase identification
- config example demonstrating the usage of default reader with standardized default data format 
- updated documentation for ranking and paraphrase identification

Siamese user

---

deeppavlov/__init__.py

add `evaluate_model` function to deeppavlov core

feature: new function evaluate_model

---

examples/tutorials/yandex_faq.ipynb

Tutorial on creating FAQ bot and connecting to Alice

Alice tutorial

---

deeppavlov/configs/faq/tfidf_logreg_en_faq.json

This PR contains paths to updated MIPT FAQ English dataset.

feat: update data file and models

---

setup.py

Puplished in https://test.pypi.org/project/deeppavlov/0.1.5a0/

chore: publish to pypi images themselves instead of their github pages

---

deeppavlov/__init__.py
deeppavlov/configs/go_bot/gobot_dstc2.json
deeppavlov/configs/go_bot/gobot_dstc2_best.json
deeppavlov/configs/go_bot/gobot_dstc2_minimal.json
deeppavlov/core/commands/utils.py
deeppavlov/core/common/check_gpu.py
deeppavlov/core/common/registry.json
deeppavlov/core/layers/tf_layers.py
deeppavlov/models/doc_retrieval/pop_ranker.py
deeppavlov/models/go_bot/network.py
deeppavlov/models/squad/squad.py
docs/apiref/models/go_bot.rst
docs/intro/config_description.rst
tests/test_quick_start.py
tests/test_tf_layers.py

* Fix `go_bot` compatibility with the previous release
* Extended support for env variables in configs

Release 0.1.5.1

---

deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json
deeppavlov/configs/odqa/ru_odqa_infer_wiki_retr_noans.json

- new odqa config with squad retr noans model
- update top n 25 -> 10 for ru tfidf ranker

feat: create odqa retr noans config, update top n for ru tfidf ranker

---

deeppavlov/core/common/chainer.py
deeppavlov/core/common/file.py
deeppavlov/models/embedders/glove_embedder.py
deeppavlov/models/ner/svm.py
deeppavlov/models/preprocessors/squad_preprocessor.py
deeppavlov/models/sklearn/sklearn_component.py

fix: dumping large files with protocol 4 for sklearn

---

deeppavlov/core/common/params.py

Support `id` field for components initialized from `config_path`.

feat: support naming of components inited from config path

---

deeppavlov/core/agent_v2/config.py
deeppavlov/core/agent_v2/rest_caller.py
deeppavlov/core/agent_v2/run.py
deeppavlov/core/agent_v2/run_dp_servers.py
deeppavlov/core/agent_v2/skill_manager.py
deeppavlov/core/agent_v2/skill_selector.py
deeppavlov/core/agent_v2/state_manager.py
deeppavlov/core/agent_v2/tests/agent_test.py
deeppavlov/core/agent_v2/tests/schema_test.py

Features:
- each skill receives its own payload which contains only dialogs for this skill
- batchified payload in rest caller
- include hellobot skill
- extend Chicthat-ODQA skill selector predictions with "hellobot"

feat: batched sselector and hellobot skill

---

deeppavlov/configs/dp_assistant/obscenity_classifier.json
deeppavlov/core/common/registry.json
deeppavlov/models/classifiers/obscenity_classifier.py

ObscenityClassifier - Rule-Based model that decides whether the sentence is obscene or not, for russian language. it returns list of strings('obscene' or 'not_obscene')
Code was tested on this script:
[agent_test.txt](https://github.com/deepmipt/DeepPavlov/files/2962474/agent_test.txt)
Results of scripts(time of runnig ObscenityClassifier.call method):
| Number of dialogs | Time |
|:-----------------------:|:------:|
|20|0:00:00.007686|
|200|0:00:00.075460|
|2000|0:00:00.739477|

Class ObscenityClassifier and config for working with him were created

---

deeppavlov/configs/dp_assistant/agent_ranking_chitchat_2staged_tfidf_smn_v4_prep.json
deeppavlov/configs/ner/ner_rus_lower_vpc_with_context.json
deeppavlov/core/agent_v2/config.py
deeppavlov/core/agent_v2/config.yaml
deeppavlov/core/agent_v2/skill_manager.py
deeppavlov/core/common/params.py
deeppavlov/models/preprocessors/person_normalizer.py

‘configs/dp_assistant/agent_ranking_chitchat_2staged_tfidf_smn_v4_prep.json‘ — конфиг ранкера с пре(пост)процессором

Preprocessor in ranker skill

---

docs/devguides/amazon_alexa.rst
docs/devguides/ms_bot_integration.rst

Added --stateful and --multiinstance flags documentation to Alexa an MS Bot Framework instegration DevGuids

Added --stateful and --multiinstance flags documentation

---

deeppavlov/core/common/chainer.py
deeppavlov/core/models/component.py
deeppavlov/core/models/tf_model.py
deeppavlov/models/elmo/elmo.py
deeppavlov/models/embedders/abstract_embedder.py
deeppavlov/models/embedders/elmo_embedder.py
deeppavlov/models/embedders/tfidf_weighted_embedder.py
deeppavlov/models/go_bot/network.py
deeppavlov/models/preprocessors/siamese_preprocessor.py
deeppavlov/models/seq2seq_go_bot/bot.py
deeppavlov/models/sklearn/sklearn_component.py

feat: universal method `destroy` in `Component` class

---

utils/telegram_utils/telegram_ui.py

Swiched on non stop polling mode in experemental telegram bot wrapper

Swiched on non stop polling mode in experemental telegram bot wrapper

---

docs/components/squad.rst

* update link to SDSJ Task B contest
* add link to SDSJ Task B dataset

fix: update links to SDSJ Task B

---

deeppavlov/configs/squad/squad_bert.json
deeppavlov/configs/squad/squad_ru_bert.json

- reduce batch size for BERT-based SQuAD models for testing

fix: reduce bs for testing

---

deeppavlov/dataset_readers/basic_classification_reader.py

Parameter `class_sep` was incorrectly changed in read method

fix: class_sep reinit from kwargs is not necessary

---

deeppavlov/models/preprocessors/one_hotter.py

Fix `OneHotter` to accept labels for every token .

fix: one_hotter for ner with pos, resolves #792

---

deeppavlov/core/commands/infer.py
deeppavlov/core/common/chainer.py

feat: add __repr__ and __getitem__ methods for chainer

---

deeppavlov/configs/ner/ner_rus_bert.json

Fixing output while tokenization in BERT preprocessor

fix: output of russian bert ner

---

deeppavlov/models/embedders/fasttext_embedder.py

Could help prevent issues like #843 and #824

docs: add a detailed error message for when fastText is not installed

---

deeppavlov/skills/aiml_skill/aiml_skill.py

This enhancement simplifies usage of AIML script in interact mode allowing to omit parameters of history and state.

enhance aiml skill by making parameters state and history optional

---

deeppavlov/configs/classifiers/insults_kaggle.json
deeppavlov/configs/classifiers/insults_kaggle_bert.json
deeppavlov/configs/classifiers/intents_dstc2.json
deeppavlov/configs/classifiers/intents_dstc2_bert.json
deeppavlov/configs/classifiers/intents_dstc2_big.json
deeppavlov/configs/classifiers/intents_sample_csv.json
deeppavlov/configs/classifiers/intents_sample_json.json
deeppavlov/configs/classifiers/intents_snips.json
deeppavlov/configs/classifiers/intents_snips_big.json
deeppavlov/configs/classifiers/paraphraser_bert.json
deeppavlov/configs/classifiers/rusentiment_bert.json
deeppavlov/configs/classifiers/rusentiment_bigru_superconv.json
deeppavlov/configs/classifiers/rusentiment_cnn.json
deeppavlov/configs/classifiers/rusentiment_elmo_twitter_cnn.json
deeppavlov/configs/classifiers/sentiment_twitter.json
deeppavlov/configs/classifiers/sentiment_twitter_preproc.json
deeppavlov/configs/classifiers/topic_ag_news.json
deeppavlov/configs/classifiers/yahoo_convers_vs_info.json
deeppavlov/configs/evolution/evolve_intents_snips.json
deeppavlov/configs/evolution/evolve_rusentiment_cnn.json
deeppavlov/configs/kbqa/kbqa_rus.json
deeppavlov/configs/ner/ner_kb_rus.json
deeppavlov/configs/ner/ner_ontonotes_bert_mult.json
deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_sep.json
deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_sep_interact.json
deeppavlov/configs/ranking/ranking_ubuntu_v2_bert_uncased.json
deeppavlov/models/evolution/evolution_param_generator.py
tests/test_configs/ranking/ranking_ubuntu_v2_bert_sep_interact_test.json
tests/test_configs/ranking/ranking_ubuntu_v2_bert_sep_test.json
tests/test_configs/ranking/ranking_ubuntu_v2_bert_uncased_test.json

feat: unify default config variables

---

deeppavlov/utils/server/server.py

Turned off dialog logging for /poller endpoint and also added filter to ignore poller requests at 'werkzeug' logger.

feat: added /poller endpoint for stand monitoring

---

deeppavlov/models/classifiers/keras_classification_model.py

fix: actually raise ConfigError when loading an inconsistent Keras model

---

deeppavlov/models/classifiers/proba2labels.py

Fixing error message from #945

fix: change error message for proba2labels

---

deeppavlov/core/data/utils.py
deeppavlov/deep.py
deeppavlov/utils/settings/socket_config.json
deeppavlov/utils/socket/socket.py
docs/index.rst
docs/integrations/socket_api.rst
docs/intro/quick_start.rst
tests/test_quick_start.py

Added risesocket mode both TCP and UNIX with tests

feat: Added `risesocket` mode

---

docs/features/models/bert.rst

updates links to re-uploaded BERT models:
- RuBERT
- SlavicBERT
- Conversational BERT
according to #969

fix: update links to fixed bert models

---

README.md

https://github.com/deepmipt/DeepPavlov/blob/docs/questionnaire/README.md

Add a questionnaire link in README.md

---

deeppavlov/utils/alexa/server.py
deeppavlov/utils/alice/alice.py
deeppavlov/utils/ms_bot_framework/server.py
deeppavlov/utils/server/server.py
deeppavlov/utils/settings/server_config.json
deeppavlov/utils/settings/socket_config.json
deeppavlov/utils/socket/socket.py
docs/integrations/amazon_alexa.rst
docs/integrations/ms_bot.rst
docs/integrations/rest_api.rst
docs/integrations/socket_api.rst
tests/test_quick_start.py

added /api endpoint to get model arg names
/apidocs -> /docs - Swagger documentation
/poller -> /probe

Model arg names from chainer + changed riseapi endpoints

---

deeppavlov/models/ranking/hybrid_ranker_predictor.py

Add check of sorted_ids len more or less than sample_size param

Add check of sorted_ids len more or less than sample_size param

---

examples/README.md

docs: create examples readme

---

examples/Pseudo-labeling for classification.ipynb
examples/classification_tutorial.ipynb
examples/evolution_results_analysis.ipynb
examples/gobot_extended_tutorial.ipynb
examples/gobot_tutorial.ipynb
examples/morphotagger_example.ipynb
examples/super_convergence_tutorial.ipynb

- python 3 in colabs by default
- gpu in colabs by default

fix: python3 in colab by default and use gpu

---

deeppavlov/core/data/utils.py
deeppavlov/models/slotfill/slotfill_raw.py

- removed tokenize_reg function

refactor: added docstrings and type annotations to core.data.utils

---

deeppavlov/core/data/utils.py

refactor: optimize and document zero pad truncate

---

deeppavlov/utils/server/server.py

1) Fixed CORS in `riseapi` mode.

Added CORS support to riseapi

---

deeppavlov/core/common/metrics_registry.json
deeppavlov/metrics/accuracy.py

fix: remove per_item_accuracy

---

deeppavlov/core/common/chainer.py
deeppavlov/core/common/params.py
deeppavlov/core/common/registry.json
deeppavlov/models/morpho_tagger/cells.py
deeppavlov/models/morpho_tagger/common.py
deeppavlov/models/morpho_tagger/common_tagger.py
deeppavlov/models/morpho_tagger/lemmatizer.py
deeppavlov/models/preprocessors/str_lower.py
docs/apiref/models/preprocessors.rst
docs/intro/configuration.rst
examples/classification_tutorial.ipynb

Also StrLower class is replaced by str_lower function
Added license info in some files and removed unnecessary imports

feat: Added ability to use functions in chainer pipe

---

README.md
deeppavlov/utils/settings/socket_config.json
deeppavlov/utils/socket/__init__.py
deeppavlov/utils/socket/socket.py
docs/integrations/socket_api.rst
tests/test_quick_start.py

fix: risesocket issue #1054

---

README.md
docs/intro/quick_start.rst

Added instructions to README for running DeepPavlov on GPU.

Added GPU run instructions

---

deeppavlov/__init__.py
deeppavlov/configs/summarization/bert_as_summarizer.json
deeppavlov/configs/summarization/bert_as_summarizer_with_init.json
deeppavlov/core/common/registry.json
deeppavlov/models/bert/bert_as_summarizer.py
docs/apiref/models/bert.rst
docs/features/models/bert.rst

- [BERT for Extractive Summarization](http://docs.deeppavlov.ai/en/latest/features/models/bert.html#bert-for-extractive-summarization)

Release 0.7.1

---

deeppavlov/utils/agent/messages.py
deeppavlov/utils/agent/rabbitmq.py

Service in agent-rabbit mode now sends error message to Agent if exception occurred during inference

feat: added service error message type

---

docs/features/skills/faq.rst

docs: fix faq doc links

---

docs/features/skills/faq.rst

correct command fidf_autofaq to tfidf_autofaq

correct command fidf_autofaq to tfidf_autofaq

---

deeppavlov/core/commands/infer.py
docs/features/overview.rst

Fix on stream prediction for models returning ndarrays

---

tests/test_quick_start.py

We can stop implement workarounds for strings as inputs for some models if we do not guarantee that the `interact` mode will work.

tests: test python inference instead of `interact` mode

---

deeppavlov/models/bert/bert_classifier.py
deeppavlov/models/bert/bert_ranker.py
deeppavlov/models/bert/bert_sequence_tagger.py
deeppavlov/models/bert/bert_squad.py

fix: allow excluding load_path argument for bert_classifier

---

README.md
deeppavlov/_meta.py
deeppavlov/metrics/accuracy.py
docs/devguides/contribution_guide.rst

Contribution guide is the main thing here. Did I miss anything?
Here it is rendered: http://docs.deeppavlov.ai/en/docs-release-0-10-0/devguides/contribution_guide.html

Docs/release 0.10.0

---

deeppavlov/core/layers/tf_layers.py
deeppavlov/requirements/nemo-asr.txt

If GRU cell is used the hidden size is `int`.

fix: fix typing

---

deeppavlov/_meta.py
requirements.txt

So that #1258 would not happen again

Fix click version requirement

---

deeppavlov/core/data/utils.py
deeppavlov/download.py
setup.py

feat/ allow s3 downloads

---

docs/features/models/popularity_ranking.rst
docs/features/models/tfidf_ranking.rst
docs/features/skills/odqa.rst

Incorrect use of the load_trained parameter removed from the documentation

---

deeppavlov/configs/go_bot/gobot_md_yaml_minimal.json
deeppavlov/dataset_readers/md_yaml_dialogs_reader.py
tests/test_quick_start.py

Gobot md yaml config fixes

---

docs/features/skills/go_bot.rst

updated RST file to get correct sequence of page sections

another attempt for better document structuring

---

examples/gobot_md_yaml_configs_tutorial.ipynb

* updated the tutorial with "run with colaboratory" link, 
* fixed rasa config version, 
* added pip install deeppavlov

gobot rasa tutorial minor changes

---

docs/intro/choose_framework.rst
docs/intro/overview.rst

Minor edits include:
- Inclusion of missing articles (the)
- Some grammatical corrections;
- Some capitalization adjustments (articles like the should not be capitalized in titles or headers);
- Some stylistic and wording improvements;
- Use of the Oxford comma convention

Minor Edits of Docs

---

deeppavlov/configs/ner/ner_collection3_m1.json
deeppavlov/models/ner/NER_model.py

fixes issue #1347 with absolute path in `ner_collection3_m1` configuration file

fix: ner_collection3_m1 #1347

---

deeppavlov/_meta.py
requirements.txt

- Fixed installation on python3.6

Release 0.14.1

---

deeppavlov/__init__.py
deeppavlov/_meta.py
deeppavlov/core/common/base.py
docs/apiref/core/common.rst

Created wrappers for `deeppavlov.core.models.component.Component` and `deeppavlov.core.common.chainer.Chainer` to simplify building pipelines building from python.

feat: Python pipeline wrappers

---

deeppavlov/__init__.py
deeppavlov/_meta.py
deeppavlov/core/common/base.py
docs/apiref/core/common.rst

- Pipeline building syntax using python is [simplified](http://docs.deeppavlov.ai/en/0.17.1/apiref/core/common.html#deeppavlov.core.common.base.Model)

Release 0.17.1

---

Jenkinsfile
deeppavlov/configs/spelling_correction/brillmoore_wikitypos_en.json
deeppavlov/core/common/requirements_registry.json

Checking test containers exit codes to prevent false-positive test results

feat: Checking test containers exit codes

---

deeppavlov/_meta.py
requirements.txt

- fix `AttributeError module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK`.

Release 0.17.3

---

deeppavlov/_meta.py
requirements.txt

Fixes `TypeError: Descriptors cannot not be created directly.` for Python 3.7.

Release 0.17.4

---

deeppavlov/core/common/metrics_registry.py
deeppavlov/core/trainers/utils.py
docs/intro/configuration.rst

Metrics from external modules could be used in configs.

feat: external metrics

---

utils/prepare/upload.py

refactor: utils/prepare/upload.py

---

README.md
deeppavlov/_meta.py
docs/index.rst
docs/intro/python.ipynb

Added python pipeline example to the documentation.

docs: python pipelines

---

README.md
deeppavlov/_meta.py
docs/index.rst
docs/intro/python.ipynb
requirements.txt
utils/prepare/upload.py

- Fixed kbqa_cq_ru on Python 3.8/3.9 ([#1609](https://github.com/deeppavlov/DeepPavlov/pull/1609))
- Added python inference pipelines example ([#1613](https://github.com/deeppavlov/DeepPavlov/pull/1613)).
- Updated model files upload script ([#1607](https://github.com/deeppavlov/DeepPavlov/pull/1607)).

Release 1.0.2

---

deeppavlov/models/torch_bert/torch_transformers_sequence_tagger.py

Fixing issue https://github.com/deeppavlov/DeepPavlov/issues/1625.

fix: CRF save in torch_transformers_sequence_tagger

---

setup.py

pip install pandoc==2.2 gives `ImportError: pip is not installed`

update: pandoc version

---

requirements.txt

- Wheel added to requirements to solve [Failed building wheel](https://stackoverflow.com/questions/53204916/what-is-the-meaning-of-failed-building-wheel-for-x-in-pip-install) for deeppavlov.

feat: added wheel to requirements

---

deeppavlov/metrics/accuracy.py
deeppavlov/metrics/fmeasure.py
deeppavlov/metrics/log_loss.py
deeppavlov/metrics/roc_auc_score.py
docs/apiref/metrics.rst

fix: issues 1262, 1522

---

deeppavlov/models/preprocessors/torch_transformers_preprocessor.py
deeppavlov/models/torch_bert/torch_transformers_sequence_tagger.py

- Fixed error when using multiple GPUs for NER models
- Fixed issue [#1642](https://github.com/deeppavlov/DeepPavlov/issues/1642)

NER bugs fixes

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

- Added Contributing Guide
- Added Code of Conduct

Community standards update

---

.readthedocs.yml
README.md
deeppavlov/_meta.py
deeppavlov/core/commands/train.py
docs/features/models/NER.ipynb
docs/features/models/multitask_bert.rst
docs/integrations/rest_api.rst
docs/intro/installation.rst
docs/intro/quick_start.rst

- Added model usage examples to Quick Start ([#1669](https://github.com/deeppavlov/DeepPavlov/pull/1669)).
- Fixed documentation building ([#1673](https://github.com/deeppavlov/DeepPavlov/pull/1673)).
- Fixed wrong link in documentation, platforms list and multitask model evaluation ([#1668](https://github.com/deeppavlov/DeepPavlov/pull/1668), [#1676](https://github.com/deeppavlov/DeepPavlov/pull/1676), [#1672](https://github.com/deeppavlov/DeepPavlov/pull/1672)).

Release 1.5.0
