deeppavlov/DeepPavlov

- deeppavlov/core/data/urls.py
- requirements-dev.txt
- tests/test_quick_start.py
After refactoring, it is possible to easily add list of query-response
pairs for every model (config), which will be used to compare pretrained
model output with expected output. Initial lists added for error_model
and ner. Also URL for downloading pretrained ner_conll2003_model added
IP-1344 #done
> test(): add test for interacting with custom queries

- README.md
Links to the go-bots removed from the Components section. Links were broken and unnecessary.
> fix: Remove go-bots from components

- examples/tutorials/04_deeppavlov_chitchat.ipynb
lazy_tokenizer was moved from deeppavlov.models.preprocessors to
deeppavlov.models.tokenizers. Change import statement accordingly
> bug: fix lazy_tokenizer.LazyTokenizer import

- deeppavlov/core/models/tf_model.py
If not trainable variable is passed to optimizer, "apply gradient" method
may fail with InvalidArgumentError. Not trainable variables
are used for saving RNN hidden state used language model task
> bug: keep only trainable variables in optimizer var_list

- deeppavlov/configs/elmo/elmo_en-1billion.json
- deeppavlov/configs/elmo/elmo_ru-news.json
- deeppavlov/configs/elmo/elmo_ru-twitter.json
- deeppavlov/configs/elmo/elmo_ru-wiki.json
- deeppavlov/models/embedders/elmo_embedder.py
The elmo interface has been updated.
Short list of changes:
- the parameter "elmo_output_names" was added to use a combination of ELMo outputs
- added "concat_last_axis" if you want to concatenate all ELMo representations
- the parameter "max_token" is added - this is the limit of a number of words per line in a batch
- added the "mini_batch_size" parameter is used to reduce  memory requirements of a device
> update (elmo): update elmo interface

- deeppavlov/skills/pattern_matching_skill/pattern_matching_skill.py
`PatternMatchingSkill` didn't work correctly with `ignore_case=True` when `patterns` contained non lower-cased words.
> fix: ignore_case in pattern_matching_skill

- tests/test_quick_start.py
Move evolution, crossvalidation and paramsearch away from the `TestQuickStart` object to reduce the count of skipped tests
> Reduce skipped tests count by 198

- deeppavlov/core/data/utils.py
Change download token file path  from `~/.deeppavlov` to `~/.deeppavlov/token`
to be able to store additional stuff in `~/.deeppavlov`
> Fixed download token file path

- deeppavlov/core/agent/dialog_logger.py
- docs/devguides/settings.rst
- utils/settings/.default/dialog_logger_config.json
- utils/settings/dialog_logger_config.json
Fixed dialog logging: for now non-unicode characters are written to dialog logs for default.
> Added ensure_ascii mode to dialog logging feature

- deeppavlov/core/common/log.py
Set logging level of matplotlib to WARNING to prevent log cluttering.
> fix: set matplotlib logging level to WARNING

- .readthedocs.yml
- docs/conf.py
With default PDF builder (pdflatex), it will be possible to easily build the docs with occasional Russian symbols only since Sphinx 2.0 release. So, changing for xelatex should work now with Sphinx <2.0, however, we need to decide, whether to provide PDF through ReadTheDocs or just make manual builds locally when it is necessary.
> Change PDF builder for correct handling of Russian

- deeppavlov/core/commands/train.py
Useful if you don't have valid/test set and dons't want your training to crash at the end.
> Ignore data_type at test if it is empty

- deeppavlov/core/commands/train.py
We do not need to evaluate a model each batch when there are no train metrics to evaluate, i.e. when using empty list for "train_metrics" config: https://github.com/deepmipt/DeepPavlov/blob/99e7d890b6d366337ac97477bf3d31c048370561/deeppavlov/configs/ranking/ranking_ubuntu_v1_mt_word2vec_smn.json#L88
It can significantly speed up the training time.
> Fix train metrics functions

- deeppavlov/configs/doc_retrieval/en_ranker_pop_enwiki20180211.json
- deeppavlov/configs/doc_retrieval/en_ranker_tfidf_enwiki20161221.json
- deeppavlov/configs/doc_retrieval/en_ranker_tfidf_wiki.json
- deeppavlov/configs/doc_retrieval/ru_ranker_tfidf_wiki.json
- deeppavlov/configs/odqa/en_odqa_infer_enwiki20161221.json
- deeppavlov/configs/odqa/en_odqa_infer_wiki.json
- deeppavlov/configs/odqa/en_odqa_pop_infer_enwiki20180211.json
- deeppavlov/configs/odqa/ru_odqa_infer_wiki.json
- deeppavlov/core/common/registry.json
- deeppavlov/models/doc_retrieval/pop_ranker.py
- deeppavlov/models/preprocessors/odqa_preprocessors.py
- docs/apiref/models/doc_retrieval.rst
- docs/components/popularity_ranking.rst
- docs/components/tfidf_ranking.rst
- docs/index.rst
- docs/skills/odqa.rst
- tests/test_configs/doc_retrieval/en_ranker_pop_wiki_test.json
- tests/test_configs/doc_retrieval/en_ranker_tfidf_wiki_test.json
- tests/test_configs/doc_retrieval/ru_ranker_tfidf_wiki_test.json
- tests/test_configs/odqa/en_odqa_infer_wiki_test.json
- tests/test_configs/odqa/en_odqa_pop_infer_wiki_test.json
- tests/test_configs/odqa/ru_odqa_infer_wiki_test.json
- tests/test_quick_start.py
- add Pop Ranker for `doc_retrieval` and `odqa`
- change doc splitting strategy from "chunks" to "paragraphs" for configs without Pop Ranker, for the best f1
> Pop Ranker for ODQA

- deeppavlov/configs/classifiers/rusentiment_cnn.json
- deeppavlov/configs/classifiers/rusentiment_elmo.json
- tests/test_quick_start.py
Dataset was removed from github due to a request from vk.com, so we can not retrain on it anymore
> tests: remove rusentiment training

- deeppavlov/core/data/utils.py
- deeppavlov/download.py
In order to pair the requested file to download with corresponding config file, the config name is added to the requested file url, for instance 
http://files.deeppavlov.ai/deeppavlov_data/ner_conll2003_v4_cpu_compatible.tar.gz?config=ner_conll2003
> Add a config name to a download url

- deeppavlov/models/classifiers/keras_classification_model.py
Found mistake in concatenation axis in one of keras_classification_model methods
> fix: concat dimension for cnn_bilstm_model

- Jenkinsfile
- setup.py
On the flake8 test selection, this PR does _not_ focus on "_style violations_" (the majority of flake8 error codes that [__python/black__](https://github.com/python/black) can autocorrect).  Instead these tests are focus on runtime safety and correctness:
* E9 tests are about Python syntax errors usually raised because flake8 can not build an Abstract Syntax Tree (AST).  Often these issues are a sign of unused code or code that has not been ported to Python 3.  These would be compile-time errors in a compiled language but in a dynamic language like Python they result in the script halting/crashing on the user.
* F63 tests are usually about the confusion between identity and equality in Python.  Use ==/!= to compare str, bytes, and int literals is the classic case.  These are areas where …
> Jenkinsfile: Add flake8 . --select=E9,F63,F7,F82 

- deeppavlov/core/data/utils.py
This PR fixes the `simple_download` function. The problem was that downloads were unsafe to interrupt, because it this cases the partially downloaded file was considered to be fully downloaded. This PR should fix this by downloading into a `*.part` file first and trying to restart the download if such a file exists.
>  fix: simple_download: make it safer to interrupt downloads

- tests/test_quick_start.py
Getting parameter names in interact_api test from `/api` endpoint.
> Feat: added /api endpoint test in riseapi mode

- Jenkinsfile
Update Jenkinsfile so that the script would work on both newer and old versions of `GitHub Branch Source Plugin` and would not require Jenkins nodes to share `workspace` directory.
> chore: checkout PR branch before testing

- deeppavlov/core/trainers/nn_trainer.py
Change from this PR allows nn_trainer to save model on existing from `train` function correclty. We assume that model saving shouldn't be ignored if its parameters were changed since the time of previous save. Since `chainer.train_on_batch` changes parameters, we need to mark the model as 'dirty'.
Previous version of DP didn't clear `_saved` flag at all. As a result, the trainer didn't save the last version of model if its `save` method was called at some point during or before training, e.g. in `_validate_first` mode.
> fix: nn_trainer, don't treat initial validation results as score improvement

- docs/features/models/syntaxparser.rst
All syntax parser headers were in the top level of the table of contents
> docs: fix syntax parser headers levels

- deeppavlov/core/data/simple_vocab.py
Added the ability to work correctly if the data has a '\t' separator in vocab's value
> Fix bug with tab sep

- deeppavlov/metrics/bleu.py
When training gobot with the gobot_config['train']['metrics'] = ["per_item_dialog_bleu"] configuration, I get the following error:
[y_p.lower().split() for y_p in y_predicted])
AttributeError: 'list' object has no attribute 'lower'
> Fixing usage of 

- deeppavlov/dataset_readers/dstc2_reader.py
- deeppavlov/metrics/bleu.py
I have added an option to provide an encoding to the dstc2_ready.py
Otherwise, I am getting an error like below:
`  File "C:\Users\..\AppData\Local\Programs\Python\Python37\lib\site-packages\deeppavlov\dataset_readers\dstc2_reader.py", line 293, in _read_from_file
cls._get_turns(json.load(open(file_path, 'rt')), with_indices=True)
File "C:\Users\..\AppData\Local\Programs\Python\Python37\lib\json\__init__.py", line 293, in load
return loads(fp.read(),
UnicodeDecodeError: 'cp949' codec can't decode byte 0xec in position 51: illegal multibyte sequence`
> Small fix to correct encoding problem

- deeppavlov/configs/classifiers/sentiment_imdb_bert.json
- deeppavlov/configs/classifiers/sentiment_imdb_conv_bert.json
- deeppavlov/core/common/registry.json
- deeppavlov/core/data/utils.py
- deeppavlov/dataset_readers/imdb_reader.py
- deeppavlov/models/classifiers/proba2labels.py
This PR implements a dataset reader for the IMDb sentiment classification dataset. It also includes a json configuration for BERT (en, cased) which is mostly the same as the configuration for rusentiment except for the max seq length and batch size (which I set to values such that I don't get out-of-memory on my hardware).
This PR also includes a fix for the `sets_accuracy` metric which should now correctly work for string labels (i.e. wrap them into sets instead converting them to sets). Also I added reporting of cached files in `download_decompress`.
> feat: Imdb sentiment dataset reader

- deeppavlov/requirements/spelling.txt
- requirements.txt
add sacremoses to main requirements.txt because it's used by nltk_tokenizer. nltk_tokenizer is used a lot by different components, and previously it didn't required extra requirements files (sacremoses was initially added only in spelling.txt).
> fix: add sacremoses to main requirements as it's used a lot

- deeppavlov/dataset_readers/basic_classification_reader.py
> feat: allow explicitly skipping datatypes in classification data reader

- deeppavlov/models/embedders/transformers_embedder.py
torch.nn.Embedding layer requires LongTensor as input. On Windows IntTensor is created by default. Explicit specification of data type fixes the problem.
> Compatibility with Windows platform.

- deeppavlov/models/morpho_tagger/lemmatizer.py
By default, `pymorphy` lemmatizes surnames to masculine form (`ивановой` - `иванов`) and patronyms to names (`ивановича` - `иван`). This PR fixes it by modifying the `UDPymorphyLemmatizer` class.
> fix: fixes PyMorphy lemmatization for surnames and patronyms

- deeppavlov/core/common/metrics_registry.json
`mean_squared_error` metric was not added to `metrics_registry.json`
> fix: add missed mse from registry

- deeppavlov/configs/classifiers/sentiment_twitter_bert_emb.json
- deeppavlov/configs/embedder/bert_sentence_embedder.json
- docs/features/models/bert.rst
- docs/features/pretrained_vectors.rst
This PR fixes a problem with pre-trained BERT models by DeepPavlov. Previous checkpoints did not include some weights that are usually used only for pre-training.
Checkpoints from DeepPavlov docs http://docs.deeppavlov.ai/en/master/features/pretrained_vectors.html#bert did not include bias parameter in NSP head.
Checkpoints from HuggingFace https://huggingface.co/DeepPavlov did not include MLM head and NSP head parameters.
Updated checkpoints:
- RuBERT (DeepPavlov/rubert-base-cased)
- Slavic BERT (DeepPavlov/bert-base-bg-cs-pl-ru-cased)
- Conversational BERT (DeepPavlov/bert-base-cased-conversational)
- Conversational RuBERT (DeepPavlov/rubert-base-cased-conversational)
Also, tokenizer configuration (tokenizer_config.json) was added to every [DeepPavlov BERT …
> fix: upload DeepPavlov BERT models with MLM & NSP heads parameters

- deeppavlov/models/kbqa/sentence_answer.py
`en_core_web_sm` is installed and used by test_inferring_pretrained_model in the same interpreter session during tests.
Spacy checks en_core_web_sm package presence with pkg_resources, but pkg_resources is initialized with interpreter,
sot it doesn't see en_core_web_sm installed after interpreter initialization.
> fix: en_core_web_sm load error during tests

- deeppavlov/configs/classifiers/paraphraser_rubert.json
- deeppavlov/core/commands/train.py
- deeppavlov/core/common/log_events.py
- deeppavlov/core/trainers/fit_trainer.py
- deeppavlov/core/trainers/nn_trainer.py
- deeppavlov/utils/settings/log_config.json
- prints during train process replaced with logger info message
- tensorboard SummaryWriter from pytorch (solved #1550)
> refactor: train logging

- deeppavlov/models/api_requester/api_requester.py
- deeppavlov/utils/server/server.py
- docs/integrations/rest_api.rst
- tests/test_quick_start.py
If Chainer returns `["a0", "a1", "a2"]`, riseapi response format is changed from `[["a0"], ["a1"], ["a2"]]` to `["a0", "a1", "a2"]`.
If Chainer returns `(["a0", "a1", "a2"], ["b0", "b1", "b2"])`, riseapi response format is changed from `[["a0", "b0"], ["a1", "b1"], ["a2", "b2"]]` to `[["a0", "a1", "a2"], ["b0", "b1", "b2"]]`.
> refactor: riseapi mode response format

- deeppavlov/core/data/simple_vocab.py
- deeppavlov/core/models/torch_model.py
- deeppavlov/core/trainers/fit_trainer.py
- deeppavlov/models/__init__.py
- deeppavlov/models/classifiers/cos_sim_classifier.py
- deeppavlov/models/classifiers/re_bert.py
- deeppavlov/models/doc_retrieval/pop_ranker.py
- deeppavlov/models/embedders/fasttext_embedder.py
- deeppavlov/models/kbqa/query_generator_base.py
- deeppavlov/models/kbqa/rel_ranking_infer.py
- deeppavlov/models/kbqa/wiki_parser.py
- deeppavlov/models/preprocessors/ner_preprocessor.py
- deeppavlov/models/preprocessors/str_utf8_encoder.py
- deeppavlov/models/sklearn/sklearn_component.py
- deeppavlov/models/spelling_correction/brillmoore/error_model.py
- deeppavlov/models/torch_bert/torch_bert_ranker.py
- deeppavlov/models/torch_bert/torch_transformers_classifier.py
- deeppavlov/models/torch_bert/torch_transformers_el_ranker.py
- deeppavlov/models/torch_bert/torch_transformers_multiplechoice.py
- deeppavlov/models/torch_bert/torch_transformers_sequence_tagger.py
- deeppavlov/models/torch_bert/torch_transformers_squad.py
- deeppavlov/models/vectorizers/hashing_tfidf_vectorizer.py
- deeppavlov/vocabs/typos.py
To make warnings in the output more perceptible:
- Set `nltk.download` to quiet mode.
- Replaced unnecessary `log.info` messages with `log.debug` in components initialization and inference.
> refactor: reduced library verbosity

- README.md
- deeppavlov/__init__.py
- deeppavlov/_meta.py
- deeppavlov/core/commands/infer.py
- deeppavlov/core/commands/train.py
- deeppavlov/deep.py
- docs/intro/quick_start.rst
- Added ``-i``/``--install`` CLI argument to install model requirements while using DeepPavlov model in any mode.
- Added ``install`` argument to ``deeppavlov.build_model``, ``deeppavlov.evaluate_model``, ``deeppavlov.train_model`` to install model requirements.
- Updated README.md and quick_start documentation.
> feat: model install argument

- deeppavlov/configs/multitask/mt_glue.json
- deeppavlov/configs/multitask/multitask_example.json
- deeppavlov/models/torch_bert/multitask_transformer.py
- tests/test_quick_start.py
> Added mtl to quickstart

- deeppavlov/core/commands/train.py
> fix: Issue 1247

- requirements.txt
Fix `ImportError: cannot import name 'Undefined' from 'pydantic.fields'` on pydantic>=2
> fix: pydantic version
